use DBproyectodaw;

INSERT INTO usuario values 
("emr","erick","4DD09B8F659E27847F94782920FB7E41B2C5AFBD7F419A4A3ED8AB7AA5B7F944","Administrador",NULL),
("bal","baldo","4DD09B8F659E27847F94782920FB7E41B2C5AFBD7F419A4A3ED8AB7AA5B7F944","Profesor",NULL),
("jom","jona","4DD09B8F659E27847F94782920FB7E41B2C5AFBD7F419A4A3ED8AB7AA5B7F944","Alumno",NULL);

INSERT INTO alumno values 
("1","Erick","Martin Robles","1994-10-29","volta5@hotmail.com",NULL),
("2","Jonathan","Martin Robles","1999-05-08","jomaron8@hotmail.com",NULL);

INSERT INTO profesor values 
("1","Heraclio","Castro Corona","1973-04-15","volta5@hotmail.com",NULL),
("2","baldo","Perez Sanchez","1955-05-09","bperezsanchez@educacyl.es",NULL);

INSERT INTO curso values 
("DAW1","Desarrollo de Aplicaciones Web 1",NULL),
("DAW2","Desarrollo de Aplicaciones Web 2",NULL),
("SMR1","Sistemas Microinformáticos y Redes 1",NULL),
("SMR2","Sistemas Microinformáticos y Redes 2",NULL);

INSERT INTO asignatura values 
("SI","SISTEMAS INFORMATICOS",NULL),
("BDD","BASES DE DATOS",NULL),
("P","PROGRAMACION",NULL),
("LDM","LENGUAJES DE MARCAS",NULL),
("EDD","ENTORNOS DE DESARROLLO",NULL),
("FOL","FORMACION Y ORIENTACION LANORAL",NULL),
("DWEC","DESARROLLO WEB EN ENTORNO CLIENTE",NULL),
("DWES","DESARROLLO WEB EN ENTORNO SERVIDOR",NULL),
("DAW","DESARROLLO DE APLICACIONES WEB",NULL),
("DIW","DISEÑO DE INTERFACES WEB",NULL),
("EIE","EMPRESA E INICIATIVA EMPRENDEDORA",NULL),
("SOM","SISTEMAS OPERATIVOS MONOPUESTO",NULL),
("AO","APLICACIONES OFIMATICAS",NULL),
("RL","REDES LOCALES",NULL),
("AW","APLICACIONES WEB",NULL),
("MME","MONTAJE Y MANTENIMIENTO DE EQUIPOS",NULL),
("SOR","SISTEMAS OPERATIVOS EN RED",NULL),
("SEI","SEGURIDAD INFORMATICA",NULL),
("SER","SERVICIOS EN RED",NULL);

INSERT INTO trabajo values 
("1","ejemplo1","examen2",NULL,NULL,"0",NULL),
("2","ejemplo2","trabajo1",NULL,NULL,"0",NULL);
